moh_report_job:
  name: "Update Moh Report Job Every 4hrs"
  cron: "0 */4 * * *"
  class: "MohReportJob"
  queue: default

nlims_sync_job:
  name: "Sync with Nlims Every 30mins"
  cron: "*/30 * * * *"
  class: "NlimsSyncJob"
  queue: default