nlims_sync_job:
  name: "Sync with Nlims Every 30mins"
  cron: "*/30 * * * *"
  class: "NlimsSyncJob"
  queue: default

home_dashboard_job:
  name: "Update Home Dashboard analytics Every 6hrs"
  cron: "0 */6 * * *"
  class: "HomeDashboardJob"
  queue: default